### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#103]
Update process for vexim2.3 started at
https://github.com/vexim/vexim2/wiki/Update-instructions-for-vexim-2.3

**Comment by Udera** [comment]
I added some stuff, now it depends on https://github.com/vexim/vexim2/pull/72

**Comment by Udera** [comment]
The wording might need some rework. But is it complete enough or do you want to add more @rimas-kudelis ?

Should we add a `VERSION`, this way users can easily identify the used version. And do we want a changelog?

**Comment by rimas-kudelis** [comment]
There's always stuff to fix in the documentation. :)

Yeah, we could add a VERSION file, why not. I guess it should say 2.2.1+git, until we decide to tag 2.3.

**Comment by rimas-kudelis** [comment]
I'm updating the instructions right now. Hope we aren't both doing this. :)

**Comment by rimas-kudelis** [comment]
Done. I don't know if there's anything else we should be adding. I'm not really a documentation writer guy. :)

**Comment by Udera** [comment]
So let's wait for feedback. Should we close here?

**Comment by rimas-kudelis** [comment]
You decide if we should close this. :)

**Comment by Udera** [comment]
That was the last issue on the vexim 2.3-milestone!

**Comment by rimas-kudelis** [comment]
How cool is that! 🍻
