### ISSUE TITLE
db, field length too short

### ISSUE THREAD

**Issue by runout-at** [vexim/vexim2#108]
The field length if `pop` and `smtp` fields in the `users` table is too short.
It's only 255 bytes which is very less on long user/domain names.
I would suggest 4096 bytes for those fields. AFAIR 4096 is the spec for path length in the file system.

**Comment by Udera** [comment]
`username` doesn't have to be a mail address, so we could allow larger usernames. `pop` and `smtp` don't need to be mail addresses (can be pipe commands), so could be longer as well.

mail addresses have a maximum length of 254 characters:
https://en.wikipedia.org/wiki/Email_address#Syntax
https://tools.ietf.org/html/rfc3696#page-6
we have currently `localpart`=192 (should be 64) and `domain`=64 (should be 255) 
but the total length must not exceed 254 characters (we do not verify that at the moment):
http://www.rfc-editor.org/errata_search.php?rfc=3696&eid=1690

**Comment by runout-at** [comment]
yes, but the fields contain the whole path like
/var/opt/vmail/mailserver.my-extra-long-domain-name.at/my-extra-long-username/Maildir
and as you stated maybe a pipe command which can also be longer than 255 char.

i run into that problem by upgrading every time because i already have bigger fields in my database. and the update script shortens the fields.

**Comment by rimas-kudelis** [comment]
Let's patch this!
We probably have to adjust maximum username length for #106 as well.

**Comment by Udera** [comment]
I added an address-check: https://github.com/Udera/vexim2/commit/3ab9e40b6282229b6d98c03daf45cebc0a59028d

@rimas-kudelis: Can you fix the db-fields? This would be part of your db-migration-script.

**Comment by rimas-kudelis** [comment]
Should we shorten `localpart` as well? It doesn't make a lot of sense to have a localpart longer than 60 characters, but it wouldn't be nice to cut it off silently as well. If we do shorten it, I think it should be mentioned in release notes or upgrade notes.

**Comment by Udera** [comment]
We should shorten localpart and put this in the release notes. I thought 
about a small tool to check the existing data base if all users have 
valid addresses. But testing my address validation, I considered that 
you would have to use extremely long mail addresses. That's very 
unlikely an issue for anybody.

**Comment by Udera** [comment]
@rimas-kudelis : Did you update the length of the database-fields? I didn't touch that because you already worked on a few changes in here: https://github.com/vexim/vexim2/pull/72

**Comment by rimas-kudelis** [comment]
No, not yet. Feel free to take over if you want to do this quicker than myself. :)

**Comment by rimas-kudelis** [comment]
Why I closed this is beyond my understanding...
