### ISSUE TITLE
Spam scanning: sa-exim or exiscan

### ISSUE THREAD

**Issue by soujak** [vexim/vexim2#131]
I think there is incoherence between documentation and configuration with respect to SpamAssassin email scanning:

1. README.md suggests the installation of sa-exim for Debian-like distribution,
2. vexim-acl-check-content.conf invokes Exim internal scan.

Hence, in Debian-like systems the default behaviour is to make every message to be processed twice by SpamAssassin, which does not look desirable.

**Comment by rimas-kudelis** [comment]
Let's fix the documentation then.
