### ISSUE TITLE
quota does not work

### ISSUE THREAD

**Issue by runout-at** [vexim/vexim2#133]
i think quota should be given in Mbyte in
/docs/debian-conf.d/transport/30_vexim_virtual_delivery

quota = ${extract{quota}{$address_data}}
should be:
quota = ${extract{quota}{$address_data}}M

**Comment by Udera** [comment]
Exim4U uses this:
````
quota = ${extract{quota}{$address_data}{${value}M}}
````
https://github.com/Exim4U/src/blob/master/etc/exim/exim.conf#L1305

@runout-at : Can you create a pull request and test it?

**Comment by runout-at** [comment]
already tested on my mailserver

**Comment by Udera** [comment]
fixed by https://github.com/vexim/vexim2/pull/149
thanks @runout-at
