### ISSUE TITLE
check passwort complexity

### ISSUE THREAD

**Issue by runout-at** [vexim/vexim2#134]
It would be very useful to check the complexity of a new/changed password
If the _clear_ field disappears we have no chance to check later if people use strong passwords. And i really know... users just don't care... I see weak passwords on mail accounts too often!

I would suggest to include something like this 
http://code.runnable.com/UmrnTejI6Q4_AAIM/how-to-validate-complex-passwords-using-regular-expressions-for-php-and-pcre
in vexim/config/functions.php: function crypt_password

**Comment by Udera** [comment]
I though about integrating such a function in the web-interface. But these programs are not very reliable, in general they would accept insecure passwords like `P@ssw0rd` but refuse secure ones like `wheelspeculumdispiritcheerful` (https://uit.stanford.edu/service/accounts/passwords/quickguide).

**Comment by runout-at** [comment]
ok. i got your point and like the link you sent, but then the password must have 20 char at least ;)

i too often see passwords like '123456' or password=username or password=firstname or with just 3 characters ...
to me it's more to prevent users from setting passwords like that than make it ultra save.

what about a configurable function, which can provide all of these versions and prevent at least very  unsecure passwords.

i will think over it and will come up with an idea soon.

**Comment by runout-at** [comment]
not tested yet but that would be an idea...
additionally we could implement a config variable to enable each test or length parameter.
if this idea will be accepted for the next release, i would volunteer to do the work.

```php
function valid_pwstrength($candidate) {
    if (preg_match_all('$\S*(?=\S{8,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d])(?=\S*[\W])\S*$', $candidate)
        || preg_match_all('$\S*(?=\S{12,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d]))\S*$', $candidate)
        || preg_match_all('$\S*(?=\S{16,})(?=\S*[a-z])(?=\S*[A-Z]))\S*$', $candidate)
        || (strlen($candidate)>20)
       )
        return TRUE;
    return FALSE;
}
/*
    Explaining $\S*(?=\S{8,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d])(?=\S*[\W])\S*$
    $ = beginning of string
    \S* = any set of characters
    (?=\S{8,}) = of at least length 8
    (?=\S*[a-z]) = containing at least one lowercase letter
    (?=\S*[A-Z]) = and at least one uppercase letter
    (?=\S*[\d]) = and at least one number
    (?=\S*[\W]) = and at least a special character (non-word characters)
    $ = end of the string

 */
```

**Comment by Udera** [comment]
Good idea.

I would pack this into a javascript and give feedback when people are entering their password. If you just take your normal password, check it via php and give a feedback "sorry, your password is too short, please try  again", that is quite annoying.

**Comment by runout-at** [comment]
thats true, but if people turn off javascript, the can enter anything.
maybe we have to check on both sides to be user friendly and to be secure.

i'm not into javascript. i can only do the php.

**Comment by runout-at** [comment]
just for the record:
from the config of the roundcube password plugin:
```php
// Require the new password to be a certain length.
// set to blank to allow passwords of any length
$rcmail_config['password_minimum_length'] = 8;

// Require the new password to contain a letter and punctuation character
// Change to false to remove this check.
$rcmail_config['password_require_nonalpha'] = true;
```

I think users will set the password in the webmail client .
Vexim is more for administrators use in such a setup.
But we should enforce strong passwords anyways to not be blamed for being the week part of the system.
