### ISSUE TITLE
acl-check-helo

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#138]
Here we have a problem:
https://github.com/vexim/vexim2/blob/master/docs/vexim-acl-check-helo.conf#L8-L11

I get this error in my logs:
```
H=(166-130.viaservers-b.com.br) [189.1.166.130] temporarily rejected EHLO or HELO 166-130.viaservers-b.com.br: failed to expand ACL string "${if and {{match{$sender_helo_name}{^[0-9]\.[0-9]\.[0-9]\.[0-9]}}{match_ip{$sender_helo_name}{@[]}}}{yes}{no}}": "166-130.viaservers-b.com.br" is not an IP address inside "and{...}" condition
```

**Comment by rimas-kudelis** [comment]
Interestingly, Exim spec says the second condition shouldn't have been evaluated:

> The sub-conditions are evaluated from left to right. The condition is true if all of the subconditions are true. If there are several “match” sub-conditions, the values of the numeric variables afterwards are taken from the last one. When a false sub-condition is found, the following ones are parsed but not evaluated.

By the way, it seems to me like the first condition would only match HELO's consisting of single-digit IP's like 8.8.8.8, or HELO's which start with such IP's (such as 8.8.8.8-foobar-whatever.com). That looks like a bug to me.

**Comment by Udera** [comment]
Just have a look at the condition below, there we are already checking for hostnames beginning with an IP address: https://github.com/vexim/vexim2/blob/master/docs/vexim-acl-check-helo.conf#L14-L16

Therefore, I only kept the check if the incoming server is using our own IP: https://github.com/vexim/vexim2/pull/139

**Comment by rimas-kudelis** [comment]
I think these idea is that either you will comment one of these conditions out, or you'll get different error messages for the case when someone sends your IP as HELO as opposed to sending someone else's (or their own) IP.

And both of these conditions seem broken by matching only single-digit IP addresses (unless that regex is not the flavor I'm familiar with.

I've added a comment on your PR.

**Comment by Udera** [comment]
you could use `match{$sender_helo_name}{[10.0.1.1]}` but I didn't find a way to use `@[]`. Even with other constructions like `forany` to extract the elements of `@[]` didn't work.
From https://github.com/Exim/exim/wiki/AclHeloTricks there is an example:
```
drop    message     = Bad helo name
        condition   = ${if  \
                         and{    \
                             {isip {$sender_helo_name}}  \
                             {match_ip{$sender_helo_name}{@[]}}  \
                         }{yes}{no}  \
                     }
```
The problem is that $sender_helo_name must not be an ip address. RFC says that you need to use brackets, so a valid `$sender_helo_name` would be `[10.0.1.1]`. In this case `isip {$sender_helo_name}` is false.

**Comment by rimas-kudelis** [comment]
> RFC says that you need to use brackets, so a valid `$sender_helo_name` would be `[10.0.1.1]`. In this case `isip {$sender_helo_name}` is false.

Are you sure this wouldn't work? Exim spec says the string is expanded first.

**Comment by Udera** [comment]
Suppose that `1.2.3.4` is the IP address of my server:

`exim4 -bh 8.8.8.8`

> 220 my.example.org ESMTP Exim 4.84_2 Wed, 20 Apr 2016 07:15:18 +0000

`EHLO [1.2.3.4]`

> processing "drop"
>   message: Bad helo name
> check condition = ${if  and{    {isip {$sender_helo_name}}  {match_ip{$sender_helo_name}{@[]}}  }{yes}{no}  }
>                 = no
> drop: condition test failed in ACL "acl_check_helo"

**Comment by Udera** [comment]
So I tried this:
```
drop    message     = Bad helo name
        condition   = ${if isip {$sender_helo_name}{yes}{no}}
```
It refuses a `EHLO 1.2.3.4` but it accepts a `EHLO [1.2.3.4]`

**Comment by Udera** [comment]
Fixed with https://github.com/vexim/vexim2/pull/139
