### ISSUE TITLE
Forward mail to different addresses for pop/imap-account

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#154]
## How to reproduce
1. Create POP/IMAP account
2. Edit settings (`adminuserchange.php`), forward mails to a list of other mail addresses, e.g. user1@example.org,user2@example.org

## Expected behavior
it should work.
and select box should allow selection of several addresses

## Actual behavior
`user1@example.org,user2@example.org is not a valid e-mail address.`

**Comment by Udera** [comment]
An address from the select box is not accepted either....

**Comment by rimas-kudelis** [comment]
I guess this must still be related to #77, as you pointed out, except that the file is different. The issue is probably with `adminuserchangesubmit.php` and `userchangesubmit.php`, which tries to validate the variable regardless of whether or not it's empty and without splitting it by commas first?

**Comment by Udera** [comment]
Yes, it is still related to #77. I think, I just didn't consider that you might want to forward to several addresses. And the select-box is not handled properly.

Shouldn't be too difficult to fix, I will have a look into it during the week.
