### ISSUE TITLE
No target details for 2.3 release

### ISSUE THREAD

**Issue by ikonia** [vexim/vexim2#165]
with a wrap up release of vexim 2.2 release happening very recently, it's made me review the 2.3 history (selfishly to look at the readiness for my own upgrades/migrations from vexim 2.2).

There appears to be no agreed feature list or tech requirements for the 2.3 release, people seem to be just adding in features as the project moves forward.

there once was a basic checklist for the 2.3 release to that there was a simple tracker as to how close the requirements where being met, this appears to not be used yet.

Could we please get a clear set of requirements, technical and functional for the 2.3 release and review where the work is being spent as I see lots of possible features discussions, and nice to have discussions, without any real direction of what is in 2.3 and what is missing to achieve that target.

This is not a complaining issue, but it is a genuine issue in that there is no plan for 2.3 therefore people do not have a goal to work towards apart from their on wants and needs, which will never really see a 2.3 release happen, as people will always want to put in more or make things better, there has to be a documented and visible goal list to meet before testing and a release of 2.3

**Comment by ikonia** [comment]
In an attempt to be a bit pro-active on this I've setup two pages in the wiki, I couldn't find anything like them, so created them.

https://github.com/vexim/vexim2/wiki/V-2.3-Functional-Requirements

https://github.com/vexim/vexim2/wiki/Vexim-2.3-technical-requirements

These are just example content of what could be published for all to see and use.

I'd also like to suggest that once these requirements are agreed and documented that something such as "trello" is used to break the requirements down into tasks so that people can see what is left, what is in progress and what is done, and if their skill set allows them, pickup a task

**Comment by Udera** [comment]
Indeed, a the little nice-to-have features don't really push the release. The last days I already tried to set the milestones in a way that `Version 2.3` contains pull requests that:

* really necessary (migration script, SSL settings)
* features already tested and we only need to decide to put them in or not

Newer features that need to be discussed or tested are tagged with `Version 2.3.1`.

To speed things up, I propose to merge all the `Version 2.3` things in the beginning of next week. All new features, we don't agree on, will be commented. Then we can take a 2 week testing and fixing period. The migration script (https://github.com/vexim/vexim2/pull/72) will be of special interest.

**Comment by ikonia** [comment]
is there actually a feature/requirement list for 2.3 though, so people can see what's included and its compatability

**Comment by Udera** [comment]
The README.md has a few requirements. But we certainly need a list of 
new features and an upgrade notice.

**Comment by rimas-kudelis** [comment]
I think it's safe to assume that there are no further **planned** features waiting for v.2.3, except perhaps migration scripts.

**Comment by Udera** [comment]
I finally merged all pending PR into master. I tested them for some time and considered the remarks that were given. So the code should be - apart from the migration scripts - ready to test.

**Comment by Udera** [comment]
There is only pending PR for the open_ssl-config, all the rest has been merged. Only documentation things are left.

**Comment by Udera** [comment]
Now, we have all code in. There are some documenation issues, only thing to be done are the update instructions and a release note. You can follow this here: https://github.com/vexim/vexim2/issues/103

**Comment by rimas-kudelis** [comment]
@Udera would you join me on gitter? I guess it's time to release 2.3, no?
