### ISSUE TITLE
MIME filter triggers on legitim files

### ISSUE THREAD

**Issue by runout-at** [vexim/vexim2#251]
Files with names like `yahoo.com!xxx.xx!1522108800!1522195199.gzip`
will trigger the MIME filter because of the '.com' domain in the name.
These are DMARC reports.

I think a '$' could help.

/etc/exim4/vexim-acl-check-mime.conf

```
{\N(?i)\.(exe|com|ade|adep|adp|bas|bat|chm|cmd|cnf|com|cpl|crt|dll|hlp|hta|inf|ins|isp|js|jse|lnk|mad|maf|mag|mam|maq|mar|mas|matmav|maw|ocx|pcd|pif|reg|scf|scr|sct|vbe|vbs|wsc|wsf|wsh|url|xnk)$\N}
```

**Comment by rimas-kudelis** [comment]
wat?

**Comment by runout-at** [comment]
sorry i hit enter too soon. edited the original now.

**Comment by rimas-kudelis** [comment]
Could you provide a PR for this?

**Comment by runout-at** [comment]
I'm just not sure about the last \N
Should the $ go before that?
