### ISSUE TITLE
Integrate Arne Schirmancher's patches into Vexim

### ISSUE THREAD

**Issue by rimas-kudelis** [vexim/vexim2#62]
https://www.schirmacher.de/display/INFO/improved+Vexim+frontend+and+bug+fixes has some improvements made over Vexim 2.2RC1:
- Filtering Spam: allows moving spam messages into their dedicated folder
- Rewriting Subject of Spam: implements per-user rules of spam subject rewriting
- Improved German translation: assuming ours hasn't been touched for years, I don't see how that could hurt

Perhaps we should integrate some (all) of these into 2.3?

EDIT: there's a page by Axel Sjøstedt, which also offers some  customizations, we should check these out as well: http://axel.sjostedt.no/misc/dev/vexim-customizations/

**Comment by Udera** [comment]
The first point is AFAIK exactly the same (or similar) that you implemented with the spam_drop-field.

**Comment by rimas-kudelis** [comment]
Indeed (except you implemented it, not me). Although Arne writes that he named the folder Junk, not Spam. We may want to rename ours as well, or perhaps make it configurable.

**Comment by rimas-kudelis** [comment]
Also, the second point apparently uses a perl script to rewrite the header. I'd prefer to avoid that if possible.

**Comment by Udera** [comment]
There are some more modifications (also rewrites header with a perl-script):
http://axel.sjostedt.no/misc/dev/vexim-customizations/
And there's a roundcube-plugin:
http://axel.sjostedt.no/misc/dev/roundcube/
https://github.com/corux/VeximAccountAdmin

**Comment by rimas-kudelis** [comment]
Yeah, since the Roundcube plugin is already on GitHub, I guess we could simply add a link to it.
regarding Axel's other customizations, it seems to me that all of them are covered by either our own code or Arne's patches. Although I've added his URL to the initial report here as well, so that we can choose what is better. :)

**Comment by Udera** [comment]
I completed the integration of the first part with the spam-filtering in this pull request: https://github.com/avleen/vexim2/pull/64

**Comment by Udera** [comment]
- [x]    Filtering Spam: allows moving spam messages into their dedicated folder: https://github.com/avleen/vexim2/pull/64
- [ ]    Rewriting Subject of Spam: implements per-user rules of spam subject rewriting
- [ ]    Improved German translation: assuming ours hasn't been touched for years, I don't see how that could hurt

Axel (only additional points):
- [ ]     SMTP, POP and IMAP over SSL (multiple certificates/hosts)?
- [ ]     Learn scripts for SpamAssassin
- [ ]     Link to Roundcube plugin
