### ISSUE TITLE
Allow enabling spamassassin and anti-virus for all domain users

### ISSUE THREAD

**Issue by rimas-kudelis** [vexim/vexim2#69]
We have disabling already, now we should allow enabling it globally as well. See #66.

**Comment by rimas-kudelis** [comment]
@Kami-no: Please use "Fixes #69" in your commit message (but also describe the commit, e.g. by pasting the title of this issue).

**Comment by Udera** [comment]
@Kami-no : ping

**Comment by Kami-no** [comment]
Hope to have time this week.

**Comment by Kami-no** [comment]
Need some translation updates:
- [ ] Disable SpamAssassin for all domain users - > SpamAssassin for all domain users
- [ ] Disable Anti-Virus for all domain users -> Anti-Virus for all domain users

Also new lines required:
- [ ] Keep unchanged
- [ ] Enable
- [x] Disable

**Comment by rimas-kudelis** [comment]
Do you have a UI mockup?
Regarding translations, I don't currently consider them a priority, but we can always send a message to our mailing list.
BTW, I think "SpamAssassin status for all domain users" would sound better than "SpamAssassin for all domain users" .

**Comment by Kami-no** [comment]
I think I've already completed this quest and ready to make a pull request. Just need to check it in action.

**Comment by rimas-kudelis** [comment]
... and how is it going?
