### ISSUE TITLE
Redirect root-mails

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#73]
Per default, root is not allowed to send mails:
https://github.com/avleen/vexim2/blob/master/docs/configure#L207

We need to add something in the documentation how to handle messages for the root-user

**Comment by rimas-kudelis** [comment]
I think this is explained quite well in the comment above the setting in question, don't you?

On 2015 m. spalis 1 d. 10:33:13 EEST, Udera <notifications@github.com> wrote:
>Per default, root is not allowed to send mails:
>https://github.com/avleen/vexim2/blob/master/docs/configure#L207
>
>We need to add something in the documentation how to handle messages
>for the root-user
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/avleen/vexim2/issues/73

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Udera** [comment]
Yes indeed. I'd like the manual be like a check list. I always forget such things when I set up a server.

Is it possible to make pull requests to the wiki here? I'd like to test some things in my repo first.

**Comment by rimas-kudelis** [comment]
Not sure, but we should try I guess

On 2015 m. spalis 1 d. 11:42:04 EEST, Udera <notifications@github.com> wrote:
>Yes indeed. I'd like the manual be like a check list. I always forget
>such things when I set up a server.
>
>Is it possible to make pull requests to the wiki here? I'd like to test
>some things in my repo first.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/avleen/vexim2/issues/73#issuecomment-144657403

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rimas-kudelis** [comment]
You can actually edit the Wiki as long as you're logged into GitHub. There doesn't seem to be any way to restrict that, so you can create and edit documentation articles without making any pull requests! :)

**Comment by Udera** [comment]
I put this in an wiki-article: https://github.com/vexim/vexim2/wiki/Optional-configurations-after-the-main-setup.

**Comment by rimas-kudelis** [comment]
I wouldn't really call this bit optional. :)
