### ISSUE TITLE
Rewriting subject

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#78]
@rimas-kudelis : You didn't want to use a perl script to rewrite the subject (https://github.com/avleen/vexim2/issues/62#issuecomment-141484762). Would you prefer php instead?
Can we use exiscan? https://github.com/Exim/exim/wiki/ExiscanExamples#marking-spam-messages-with-extra-headers-and-subject-tag
I haven't tested this: http://www.gossamer-threads.com/lists/exim/users/59918#59918

**Comment by Z3po** [comment]
Please don't. Don't fork script-pipes from exim for rewriting mails...that's feels dirty.

**Comment by rimas-kudelis** [comment]
> You didn't want to use a perl script to rewrite the subject (#62 (comment)). Would you prefer php instead?

I was talking about using external scripts in general. I find it difficult to believe that this can't be implemented by ordinary means (that is, by adding some more magic to the config file).

**Comment by Z3po** [comment]
Regarding the comment: http://www.gossamer-threads.com/lists/exim/users/59918#59918 you can't do that at acl_smtp_data time. This ACL is called only once for multiple recipients and if you'd like to have user configured Subject lines that doesn't work.
You need to do that in the mail transport. I'll check if that works...

**Comment by Z3po** [comment]
Probably the following works:
Save the subject line in a variable at data-acl.
If configured in the MySQL remove the subject header and add it back in with corresponding Prefix in the router.
Should that be included in the 2.3 release already?

**Comment by Z3po** [comment]
I've again checked the documentation:
http://www.exim.org/exim-html-current/doc/html/spec_html/ch-message_processing.html -> 17. Adding and removing header lines in routers and transports
there's the following Example:

    headers_remove = subject
    headers_add = Subject: new subject (was: $h_subject:)

That looks good. If we need that for the 2.3 release I'll create the corresponding router snippet.

**Comment by Z3po** [comment]
Still I have a question about that one:
What is the sa_tag value about if not to tag the message (with probably rewriting the subject)?
Is there a valid scenario to just add a "X-New-Subject" Header to "tag" the message?
Do we need the new "on_rewritesubject" field for that?

Please enlighten me...i don't get it completely...

**Comment by Udera** [comment]
I was thinking of putting a new variable into the user database, on_rewrite.
And then I would add the header like you wrote in https://github.com/vexim/vexim2/issues/78#issuecomment-147238918
with
````
if score>tag && on_rewrite -> subject: ****SPAM**** old_subject
else subject: old_subject
````

**Comment by Z3po** [comment]
I'm not completely satisfied here...what is the benefit of such an option?
Are there any real-world usecases of having my Mail Subject lines uglyfied by Spam-count numbers?
I always wondered about people answering to mails with these strange subject lines...

**Comment by Udera** [comment]
There were two patches (Schirmacher/Sjøstedt) including such a header rewrite for spam-mails. Because we wanted to make vexim 2.3 usable for all vexim-users, we thought of putting this feature.

Ideally, only spam-mails get this ugly subject lines. I don't know if this can make sense for some forwarding accounts. Or if you use POP3 and you don't have folders?

**Comment by Z3po** [comment]
Hmm...still using pop3? Anyone?

So beside the facts someone implemented these: Do we want to add a subject manipulation mechanism? I can't currently think of (beside the pop3 thing) any real world usage.

**Comment by rimas-kudelis** [comment]
Quoting the original case for rewriting subject:
> By default, spam is only tagged in the X-Spam headers. Since users cannot tweak their own spam settings more than setting the score thresholds, and subject tagging still seems to be popular to identify spam and make client side filters, I added automatic tagging of "****SPAM*****" and spam score in subject.

I have no opinion whether or not this is necessary today. Maybe it is, maybe not. Perhaps it would be best to ask on the mailing list?

**Comment by rimas-kudelis** [comment]
I'd like to assume that people who know how to use e-mail filters to filter spam would know about `X-Spam-*` headers and how to see them as well, but maybe I'm wrong.
On the other hand, e-mail clients got smarter over the years, and today there are other ways to mark spam than to write filters by hand.

**Comment by Udera** [comment]
Personally, I don't use it. I prefer IMAP + sieve ;-) I know some users which are still using POP3 (no subject rewriting).

**Comment by rimas-kudelis** [comment]
>> I have no opinion whether or not this is necessary today. Maybe it is, maybe not. Perhaps it would be best to ask on the mailing list?
> 
> done: https://groups.google.com/forum/#!topic/vexim/6BK1F1_H6Jk0

Two weeks passed, no reply. Let's just assume our users don't really care about this feature, so we can freely decide ourselves if we want to continue working on it. Do we?

**Comment by Udera** [comment]
Let's leave it and release vexim2.3. If there is someone coming up, we can do a 2.3.1 version.

**Comment by rimas-kudelis** [comment]
Let's close this then and reopen if necessary.
