### ISSUE TITLE
Update the example exim config file and make sure that it works

### ISSUE THREAD

**Issue by rimas-kudelis** [vexim/vexim2#8]
I suspect that after 4effffa, our config might be partially unusable, because $tls_advertise_hosts is not defined in it, which IIRC means that STARTTLS won't be available, which in turn means that the user will never be able to authenticate to send email.

Furthermore, the variables `$auth1`, `$auth2` and `$auth3`, which replaced `$1`, `$2` and `$3` in 0aa951a, don't work in Exim3. I don't think this is a problem, however, this means we should update our README file as well.

**Comment by ikonia** [comment]
started putting in some options to give you a basic out of the box working config

**Comment by Udera** [comment]
In the meantime, the config-files should be very similar. All the routers and transport section are identical. The authentication as well.

**Comment by Udera** [comment]
> I quickly checked in the debian-documentation. There is already a
>  debian script (update-exim4.conf) merging all the config-files
>  together in a single file (/var/lib/exim4/autogenerated). But at the
>  moment, the debian configuration in conf.d/ is not fully working
>  (parts of configure-file and vexim-acls-... are missing).
> What do you mean?

Ok, the vexim-acl-files are already linked in the conf.d-section: https://github.com/avleen/vexim2/blob/master/docs/debian-conf.d/main/00_vexim_listmacrosdefs#L39-L40

What I meant with merging the split-files of exim: Debian seems to assemble all the split files itself:
https://wiki.debian.org/Exim#Split_file

We could use this process to compare the configurations of the single file and the split files. In the future, we modify only the split files and autogenerate the assembled file. Would such an assembled file work in other systems (FreeBSD, CentOS, ...)?

**Comment by rimas-kudelis** [comment]
I suppose it should work, yes.

Although (and I think I said in one of the other issues) I'm still uncertain whether or not we should actually ship full config files in our sources. On one hand, if we ship full config (whether split Debian-style or in a single file), we make much more choices for the user than is necessary for SQL virtual mailboxes to work. On the other hand, even our current Debian-style files make some of these assumptions (at least the assumption about encryption being enabled). Furthermore, Exim is currently the only application for which we do ship a full config, and even though we are called Vexim, we aren't really tied to Exim in any way.

Perhaps our Wiki would be a better place for config files? If not, I suggest that we at least rename the `docs` folder to `examples` or something similar, and make all config examples live at the same level (ironically, this would make Exim the only software with a dedicated directory for its examples in our tree, at least for now).

I honestly don't know what the best way to proceed with this is. I guees I need an :8ball:... :-)

**Comment by rimas-kudelis** [comment]
I've just committed some changes to the Exim config: f63539df92285ae793d1aa3fc5a0f953cb351f38.

Regarding Debian, I wonder if it's possible for an unrelated package to hook into `exim4-config`'s configuration in any way. Debian allows both split config and one-file config. The files we provide are focused on split-config case only, which is not always the case.

I like how Debian allows the user to define macros to toggle some of the functionality in Exim. Perhaps instead of asking the user to comment out or uncomment things, we should use macros in our `configure` file as well?

**Comment by Z3po** [comment]
What about just supplying the conf.d files and stop serving a always "broken" full-blown config file?

**Comment by Udera** [comment]
Do other systems use the conf.d-files as well? From what I've read on the documentation, you need to merge all these files in Debian as well. If you don't use this conf.d/-setting, then it will be difficult to figure out where to put all these lines (and what other lines might be required).

@rimas-kudelis These macros are very nice. For configuration, you can keep (nearly) all settings at one place and you don't need to change it throughout the file(s).

**Comment by Z3po** [comment]
OK. I'm conviced here. Let's use the debian conf.d mechanism, so we just have to maintain the conf.d directories and use the latest debian template for generating the "full" config. I'll give that a try and come back if that works like we thought.

**Comment by Z3po** [comment]
Looks good. I'll try to get a working version together untill Weekend.

**Comment by Z3po** [comment]
Hi guys,
late but hopefully not too late I've taken a look into that:

https://github.com/Z3po/vexim2/tree/implement_update_exim4conf

please checkout and let me know what you think about that approach.
All necessary files are within the eximconf folder.
You need to have the update-exim4.conf script locally available (e.g. by installing the exim4-conf package on debian).
I've copied the conf.d directories from a normal wheezy installation and symlinked our adjustment conf.d files into the corresponding directories. Now running generate.sh will call update-exim4.conf and generate the "configure" file within the very same directory.
Please do me a favour and check if the file changes in any way if you call it on your machine to the one I already generated and added to the repository.
I still think there's space for improvements:
* Within the generate.sh script copy the conf.d directories from the local filesystem -> *cp -R /etc/exim4/conf.d ./*
* Iterate on all conf.d subfolders within the docs/debian-conf.d and symlink the available files to the locally generated copy of the system conf.d folder
* call update-exim4.conf ....

That way we don't need to copy all files and make sure they are kept in sync with the debian package files but we will always have the locally available versions used.

Downside:
This will break if you have local modifications and use split config files. This could be worked around by using a changeroot or something similar for generating the full config file.

Please Let me know what you think

**Comment by Udera** [comment]
What I liked in the previous conf.d/-files, there are only the files needed to run vexim. All other configuration options is up to the decision of the user. The documentation can give some tips what options to use (Blacklists, SPF, ...).

Now everything would be focused on a specific debian-version. Is this configuration compatible with all exim-versions? Compared to the current `configure`-file there is even more clutter.
Do you run other systems and can tell which distributions use the conf.d/-approach?

**Comment by rimas-kudelis** [comment]
I think we could take from Debian only the parts that we want, which are not necessarily all parts. Perhaps we shouldn't even have `conf.d` files in the repository, but instead provide a Debian package, or a script to build one. The script could extract the necessary parts of the configure file into vexim-specific `conf.d` files, the only potential problem I see with this is that we might end up having to define more Debian-like variables than we actually need, but in my opinion, that's not a big deal: it's probably still better than having to maintain two sets of settings in sync.

On the other hand, as long as it's just two sets (not five or seven), I think we can afford that as well.

**Comment by Z3po** [comment]
Do you run other systems and can tell which distributions use the conf.d/-approach?
Well i took a look around and nobody really uses the conf.d approach then debianic Systems.

     The script could extract the necessary parts of the configure file into vexim-specific conf.d files
Well please not. That sounds like we want to delete files within the conf.d directories of debian Systems which have been put there on purpose. The conf.d approach is so mighty because it doesn't matter if there still are other files available. Therefore no cleanup needs to happen. If I'd like to add mailman functionality, I install the package and all specific routers will be included in my conf.d directories.

    On the other hand, as long as it's just two sets (not five or seven), I think we can afford that as well.
I see your point in having "too much" in the full configure file. But that shouldn't be an issue. We could either patch the debian specific conf.d files or just not include the ones we don't need (that should probably be prefered than messing up something..). This way we won't have to maintain anything other than the conf.d snippets which are easier to handle in my opinion than going through a huge and ugly full-config file.

**Comment by Z3po** [comment]
What I liked in the previous conf.d/-files....

Oh I think we're talking about different things here...
The Idea I had was about supplying a mechanism to generate a full-config file out of the snippets we're maintaining. That's a mechanism to stop manually updating the configure file within the doc directory but to generate it with the maintained conf.d snippets. It's not meant to replace the conf.d files.

**Comment by rimas-kudelis** [comment]
>>  The script could extract the necessary parts of the configure file into vexim-specific conf.d files

> Well please not. That sounds like we want to delete files within the conf.d directories of debian Systems which have been put there on purpose. The conf.d approach is so mighty because it doesn't matter if there still are other files available. Therefore no cleanup needs to happen. If I'd like to add mailman functionality, I install the package and all specific routers will be included in my conf.d directories.

I think you misunderstood me. My idea was that we could probably generate Debian-specific files from the configure file we supply, during the generation of .deb package. I certainly wasn't going to remove any Debian stock files from /etc/exim/

**Comment by Udera** [comment]
Just coming back to the initial issue: We already fixed the authentication in the config-file. All the changes over the last months were put in both configurations (single file, conf.d/-folder). So there shouldn't be differences any more. Or is there still anything missing? @rimas-kudelis 
If not, we can close this.

**Comment by rimas-kudelis** [comment]
Probably just a review? If all is fine and both versions work, this can be closed.

**Comment by rimas-kudelis** [comment]
Come to think of it, I'm beginning to lean towards @Z3po's solution: why not have a bunch of `conf.d` files and provide a script to concat them into a single `configure` file? We should be able to copy them verbatim from a Debian package (it doesn't seem like they update these config files often), all we would need is to adapt update-exim4-config for our needs (that is, to generate a config in our folder, not in `/etc/exim4`, and not to restart Exim after the job is done). This way we would have just one Exim4 configuration to maintain and wouldn't have to worry about changing stuff in two places.
In fact, we could even pre-concatenate some of files, if that would seem cleaner, although I'm not sure it's worth the trouble.

**Comment by Udera** [comment]
> why not have a bunch of conf.d files and provide a script to concat them into a single configure file?

@rimas-kudelis : Is this something you want to do for the 2.3-release?

The initial issue of a working `docs/configure` is solved. I went through the transports and routers. In the end it is hard to compare them exactly as the `conf.d`-version might have some additional stuff from your distribution.

**Comment by Udera** [comment]
There is still one open report where both configurations differ: https://github.com/vexim/vexim2/issues/109
A follow up for an automated generation of the combined configuration file: https://github.com/vexim/vexim2/issues/160

Therefore, closing here.
