### ISSUE TITLE
Behavior disabled domain/accounts

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#88]
In the testing-procedure, I found this:
https://github.com/vexim/vexim2/blob/master/docs/checklist.txt#L71-L73

Disabled domain -> postmaster can login, user can't (all should be able to login)
Disabled account -> user can login (should fail)

I don't know, where this feature was lost and if there were some security aspects. Do we want this back? @rimas-kudelis

**Comment by Udera** [comment]
remark: This pull request didn't make a difference: https://github.com/vexim/vexim2/pull/84
So we could merge this.

**Comment by rimas-kudelis** [comment]
I suppose we should fix it, especially considering how simple it must be. :)
